apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: khownar-com-tls
spec:
  secretName: khownar-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: khownar.com
  dnsNames:
    - khownar.com
    - www.khownar.com